//! The request context and the [`FromRequest`] dependency-injection trait.
//!
//! Every handler parameter that is not a path parameter is resolved through
//! [`FromRequest`]. Built-in extractors (such as [`State`](crate::State),
//! [`BearerToken`], and [`Json`](crate::Json)) implement it directly, and the
//! `#[tork::dependency]` macro generates an implementation for user-defined
//! dependencies. There is no blanket implementation, which keeps the trait free
//! of coherence conflicts.

use std::sync::Mutex;

use http::{HeaderMap, Method, Uri};

use crate::body::ReqBody;
use crate::error::{Error, Result};
use crate::state::{AppStateRef, StateMap};

pub mod body;
pub mod header;
pub mod path;
pub mod valid;

pub use header::BearerToken;
pub use path::{FromPathParam, __extract_path_param};
pub use valid::Valid;

/// Raw path parameters captured by the router, in match order.
#[derive(Debug, Default, Clone)]
pub struct PathParams {
    entries: Vec<(String, String)>,
}

impl PathParams {
    /// Creates an empty set of path parameters.
    pub fn new() -> Self {
        Self::default()
    }

    /// Appends a captured parameter and its raw value.
    pub fn push(&mut self, name: String, value: String) {
        self.entries.push((name, value));
    }

    /// Returns the raw value captured for `name`, if any.
    pub fn get(&self, name: &str) -> Option<&str> {
        self.entries
            .iter()
            .find(|(key, _)| key == name)
            .map(|(_, value)| value.as_str())
    }

    /// Returns `true` if no path parameters were captured.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Returns the number of captured path parameters.
    pub fn len(&self) -> usize {
        self.entries.len()
    }
}

/// Everything an extractor needs to resolve a value from the current request.
///
/// Holds the request head (method, URI, headers, extensions), the captured path
/// parameters, a handle to the application state, and the request body. The body
/// can be taken at most once; see [`RequestContext::take_body`].
pub struct RequestContext {
    head: http::request::Parts,
    path_params: PathParams,
    state: AppStateRef,
    body: Mutex<Option<ReqBody>>,
}

impl RequestContext {
    /// Builds a new request context.
    pub fn new(
        head: http::request::Parts,
        path_params: PathParams,
        state: AppStateRef,
        body: ReqBody,
    ) -> Self {
        Self {
            head,
            path_params,
            state,
            body: Mutex::new(Some(body)),
        }
    }

    /// Returns the request method.
    pub fn method(&self) -> &Method {
        &self.head.method
    }

    /// Returns the request URI.
    pub fn uri(&self) -> &Uri {
        &self.head.uri
    }

    /// Returns the request headers.
    pub fn headers(&self) -> &HeaderMap {
        &self.head.headers
    }

    /// Returns the full request head.
    pub fn head(&self) -> &http::request::Parts {
        &self.head
    }

    /// Returns the application state map.
    pub fn state(&self) -> &StateMap {
        self.state.as_ref()
    }

    /// Returns the captured path parameters.
    pub fn path_params(&self) -> &PathParams {
        &self.path_params
    }

    /// Returns the raw value of the path parameter named `name`, if captured.
    pub fn path_param(&self, name: &str) -> Option<&str> {
        self.path_params.get(name)
    }

    /// Takes ownership of the request body.
    ///
    /// # Errors
    ///
    /// Returns a `400 Bad Request` error if the body was already taken, since a
    /// body can only be consumed by a single extractor.
    pub fn take_body(&self) -> Result<ReqBody> {
        self.body
            .lock()
            .expect("request body mutex poisoned")
            .take()
            .ok_or_else(|| Error::bad_request("request body has already been consumed"))
    }
}

/// Produces a value from the current request to satisfy a handler parameter.
///
/// Implemented directly by built-in extractors and generated by
/// `#[tork::dependency]` for user dependencies. Resolution is always statically
/// dispatched. The returned future is `Send` so the enclosing handler future is
/// `Send`, as required by the server.
pub trait FromRequest: Sized + Send {
    /// Resolves `Self` from the request context.
    ///
    /// An `Err` short-circuits request handling and is rendered as an HTTP error
    /// response.
    fn from_request(
        ctx: &RequestContext,
    ) -> impl std::future::Future<Output = Result<Self>> + Send;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::body::box_body;
    use crate::error::ErrorKind;
    use bytes::Bytes;
    use http_body_util::Full;
    use std::sync::Arc;

    fn test_context(path_params: PathParams, body: &'static str) -> RequestContext {
        let head = http::Request::new(()).into_parts().0;
        let body = box_body(Full::new(Bytes::from_static(body.as_bytes())));
        RequestContext::new(head, path_params, Arc::new(StateMap::new()), body)
    }

    #[test]
    fn path_param_lookup_and_parse() {
        let mut params = PathParams::new();
        params.push("user_id".to_owned(), "42".to_owned());
        let ctx = test_context(params, "");

        let parsed: i64 = __extract_path_param(&ctx, "user_id").unwrap();
        assert_eq!(parsed, 42);
    }

    #[test]
    fn invalid_path_param_is_unprocessable() {
        let mut params = PathParams::new();
        params.push("user_id".to_owned(), "not-a-number".to_owned());
        let ctx = test_context(params, "");

        let error = __extract_path_param::<i64>(&ctx, "user_id").unwrap_err();
        assert_eq!(error.kind(), ErrorKind::Unprocessable);
    }

    #[test]
    fn body_can_only_be_taken_once() {
        let ctx = test_context(PathParams::new(), "hello");

        assert!(ctx.take_body().is_ok());
        let error = ctx.take_body().unwrap_err();
        assert_eq!(error.kind(), ErrorKind::BadRequest);
    }
}
